### ISSUE TITLE
Qatar has no value for GDP per capita 

### ISSUE THREAD

**Issue by cmdcolin** [factbook/factbook.csv#3]
c2004.csv is blank for Qatar even though it is at the top

According to http://factbook.github.io/qa

```
GDP - per capita (PPP):
$143,400 (2014 est.)
$135,100 (2013 est.)
$127,100 (2012 est.)
note: data are in 2014 US dollars
```

The central factbook site lists 2015 estimate as well $132,100 (2015 est.)

**Comment by geraldb** [comment]
Thanks for reporting. The csv lists are provided by the CIA itself (it's NOT rebuild somehow from the web page). Please check if the GDP is included in the .csv / text file provided by the CIA.  If you're interested in fixing the data, please join the [forum and say hello](http://groups.google.com/group/openmundi). Cheers.

**Comment by cmdcolin** [comment]
Interesting. I'll see what I can do, very interesting project :)!
